"""Condensed the User table to hold the goals too, and the User_Program table holds their lifting goals for the lifting section quiz.

Revision ID: b8c05741627c
Revises: 693c2e134907
Create Date: 2026-10-09 18:58:58.670335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c05741627c'
down_revision: Union[str, Sequence[str], None] = '693c2e134907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.add_column('user_programs', sa.Column('goal', sa.String(), nullable=False))
    op.add_column('user_programs', sa.Column('experience_level', sa.Integer(), nullable=False))
    op.add_column('user_programs', sa.Column('days_available', sa.Integer(), nullable=False))
    op.add_column('user_programs', sa.Column('equipment_available', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('current_weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('goal_weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('workouts_per_week_goal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sleep_goal', sa.Float(), nullable=True))
    op.drop_constraint(op.f('workout_sets_exercise_id_fkey'), 'workout_sets', type_='foreignkey')
    op.drop_constraint(op.f('workout_sets_workout_id_fkey'), 'workout_sets', type_='foreignkey')
    op.create_foreign_key(None, 'workout_sets', 'workouts', ['workout_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'workout_sets', 'exercises', ['exercise_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workout_sets', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workout_sets', type_='foreignkey')
    op.create_foreign_key(op.f('workout_sets_workout_id_fkey'), 'workout_sets', 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('workout_sets_exercise_id_fkey'), 'workout_sets', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'sleep_goal')
    op.drop_column('users', 'workouts_per_week_goal')
    op.drop_column('users', 'goal_weight')
    op.drop_column('users', 'current_weight')
    op.drop_column('user_programs', 'equipment_available')
    op.drop_column('user_programs', 'days_available')
    op.drop_column('user_programs', 'experience_level')
    op.drop_column('user_programs', 'goal')
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('goal', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('experience_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('days_available', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipment_available', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
